package com.inventario.enums;

public enum Category {
    FRUTAS_Y_VERDURAS,
    CARNICERÍA_Y_POLLERÍA,
    PESCADERÍA,
    LÁCTEOS,
    FIAMBRERÍA_Y_QUESERÍA,
    PANADERÍA_Y_REPOSTERÍA,
    ALMACÉN_Y_ABARROTES,
    LEGUMBRES_Y_CEREALES,
    ACEITES_Y_CONDIMENTOS,
    ENLATADOS_Y_CONSERVAS,
    DESAYUNO_Y_MERIENDA,
    SNACKS_Y_COPETÍN,
    BEBIDAS_SIN_ALCOHOL,
    BEBIDAS_CON_ALCOHOL,
    CONGELADOS,
    LIMPIEZA_DEL_HOGAR,
    HIGIENE_Y_CUIDADO_PERSONAL,
    MASCOTAS,
    BAZAR_Y_HOGAR,
    FARMACIA_Y_PERFUMERÍA
}
